"""
Django settings for aichat project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
import os
from pathlib import Path
import pymysql
import yaml

pymysql.install_as_MySQLdb()


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-0931d@qc=p$y0#pg7l1hfz6c(3!!ow*d1rp2699nft-k%@39p+'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['*', ]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'django_filters',
    'drf_spectacular',
    # 'django_celery_results',  # celery结果
    # 'django_celery_beat',     # celery定时任务

    'users',
    'assistant',
    'subscribe',
    'llm',
    'usage'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware', # 加入中间键 位置必须在这里 不能在其他位置
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware'
]

ROOT_URLCONF = 'aichat.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'aichat.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'aichat',
        'HOST': '192.168.3.5',
        'PORT': 3306,
        'USER': 'admin',
        'PASSWORD': 'Hello@0509'
    },
}

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://192.168.3.5:6379/1",
        #"LOCATION": "redis://115.193.173.239:36379/1",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}


REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',
    ),
    'DEFAULT_FILTER_BACKENDS': (
        'django_filters.rest_framework.DjangoFilterBackend',
    ),
    'DEFAULT_PAGINATION_CLASS': (
        'aichat.pagination.StandardResultsPagination',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
        'rest_framework.permissions.AllowAny',
    ),
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.TokenAuthentication',
    ),
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}
SPECTACULAR_SETTINGS = {
    'TITLE': '齐物 AI 平台接口',
    'DESCRIPTION': '齐物 AI 平台接口',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'SCHEMA_PATH_PREFIX': r'/v1/',
    # OTHER SETTINGS
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Asia/Shanghai'
USE_I18N = True
USE_TZ = True




STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'staticfiles'),

]

MEDIA_ROOT = os.path.join(BASE_DIR, 'data/media')
MEDIA_URL = '/media/'
FILE_UPLOAD_DIR = os.path.join(MEDIA_ROOT, 'uploadsfile')
LIVEROOM_DATA_DIR = os.path.join(MEDIA_ROOT, 'liveroom')

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
LOGGER_DIR = os.path.join(BASE_DIR, 'logs')

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{asctime}] {levelname} [{pathname} {lineno} {funcName}] {message}',
            'style': '{',
        },
        'simple': {
            'format': '[{asctime}] {levelname} [{pathname} {lineno} {funcName}] {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'DEBUG',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOGGER_DIR, 'aichat.log'),
            'formatter': 'verbose'
        },
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'simple'
        },
    },
    'loggers': {
        '': {
            'handlers': ['file', 'console'],
            'level': os.getenv('DJANGO_LOG_LEVEL', 'INFO'),
            'propagate': True,
        },
    },
}


OCEANENGINE_SERVER = 'https://api.oceanengine.com'
OCEANENGINE_APP_ID = 1800457541205164
OCEANENGINE_SECRET = 'bd6135ea43505aac953b8c4a5eeaf0c5182f3366'
OCEANENGINE_SCOPE = '[24000000,20120000,23000000,200000005,21120000,200000001,25000000,22100300,22101100,20110000,22100200,22100400,22100500,22101000,22100600,22101300,26000000,300000001,21010000]'
OCEANENGINE_CALLBACK_URL = 'https://qw.fengidri.me/oauth/callback/'
OCEANENGINE_OATUH_REDIRECT_URL = 'http://127.0.0.1:8000/qianchuan/oauth'

DOUYIN_TIKTOK_DOWNLOAD_API_SERVER = 'http://aichat_Douyin_TikTok_Download_API'


# google 搜索配置
GOOGLE_SEARCH_API_SERVER = ''
GOOGLE_SEARCH_API_KEY = ''
GOOGLE_SEARCH_API_ENGINE_ID = ''


LIVEROOM_DATA_ANALYZE_ASSISTANT = 59

OPENAI_API_KEY = ''
OPENAI_BASE_URL = ''
OPENAI_PROJECT = ''
OPENAI_ORGANIZATION = ''

ANTHROPIC_API_KEY = ''
ANTHROPIC_BASE_URL = ''

# deepseek相关配置
DEEPSEEK_API_KEY = 'sk-6544c928a00b478ca6191b4a3d7aba63'
DEEPSEEK_BASE_URL = 'https://api.deepseek.com/v1'

# 豆包相关配置
DOUBAO_API_KEY = ''
DOUBAO_BASE_URL = ''

# 豆包vision类的模型
DOUBAO_VISION_MODEL = ['ep-20241212141315-g8nnd', ]
# 默认模型，主要用于title生成
DOUBAO_DEFAULT_MODEL = 'ep-20241209112050-lp69k'


SUPPORT_MODELS = {
    'openai': {
        'name': 'openai',
        'model_list': [{
            'name': 'gpt-3.5-turbo',
            'value': 'gpt-3.5-turbo',
        }, {
            'name': 'gpt-4o',
            'value': 'gpt-4o',
        }, {
            'name': 'gpt-4',
            'value': 'gpt-4',
        }, {
            'name': 'gpt-4-turbo',
            'value': 'gpt-4-turbo',
        }]
    },
    'anthripic': {
        'name': 'Anthripic',
        'model_list': [{
            'name': 'claude-3-5-sonnet-20241022',
            'value': 'claude-3-5-sonnet-20241022',
        }, {
            'name': 'claude-3-5-sonnet-20240620',
            'value': 'claude-3-5-sonnet-20240620',
        }, {
            'name': 'claude-3-haiku-20240307',
            'value': 'claude-3-haiku-20240307',
        }, {
            'name': 'claude-3-opus-20240229',
            'value': 'claude-3-opus-20240229',
        }, {
            'name': 'claude-3-sonnet-20240229',
            'value': 'claude-3-sonnet-20240229',
        }]
    },
    'doubao': {
        'name': '豆包',
        'model_list': [{
            'name': 'doubao-pro-32k',
            'value': 'ep-20241209112050-lp69k',
        }, {
            'name': 'doubao-pro-32k[box]',
            'value': 'bot-20241209112138-59wl9',
        }]
    },
    'deepseek': {
        'name': 'DeepSeek',
        'model_list': [{
            'name': 'DeepSeek-V3',
            'value': 'deepseek-chat',
        }, {
            'name': 'DeepSeek-R1',
            'value': 'deepseek-reasoner',
        }]
    }
}

# 试用用户可以免费使用的助手id
USER_FREE_USE_ASSISTANT_IDS = ['63', '60', '56']
# 试用用户每日可以免费使用的消息数量
USER_FREE_USE_MSG_COUNT = 20
# 试用用户每条消息限制的长度
USER_FREE_USE_MSG_LENGTH = 100
# 试用用户试用时长
USER_FREE_USE_DAYS = 7


ALIYUN_ACCESS_KEY_ID = ''
ALIYUN_ACCESS_KEY_SECRET = ''
ALIYUN_SMS_ENDPOINT = ''
ALIYUN_SMS_SIGN_NAME = ''
ALIYUN_SMS_TEMPLATE_CODE = ''


LOGIN_URL = '/login/'

CSRF_TRUSTED_ORIGINS = ['http://127.0.0.1:8000', 'http://127.0.0.1:8080']

# # 跟缓存的redis配置类似，使用不同的库就行
# CELERY_BROKER_URL = "redis://192.168.3.5:6379/0"
# # 时区跟Django的一致
# CELERY_TIMEZONE = TIME_ZONE
# # 不使用utc，所以在定时任务里面的时间应该比上海时间少8小时，比如要设置本地16:00执行，那么应该在定时里面设置成8:00
# CELERY_ENABLE_UTC = True
# # 应对django在使用mysql的时候设置USE_TZ = False导致的报错
# # DJANGO_CELERY_BEAT_TZ_AWARE = False
# DJANGO_CELERY_BEAT_TZ_AWARE = True
# # 支持数据库django-db和缓存django-cache存储任务状态及结果
# CELERY_RESULT_BACKEND = "django-db"
# CELERY_CACHE_BACKEND = 'django-cache'
# # 将任务调度器设为DatabaseScheduler
# CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'
# # celery内容等消息的格式设置，默认json
# CELERY_ACCEPT_CONTENT = ['application/json', ]
# CELERY_TASK_SERIALIZER = 'json'
# CELERY_RESULT_SERIALIZER = 'json'
# # 每个 worker 最多执行n个任务就会被销毁，可防止内存泄露
# CELERY_WORKER_MAX_TASKS_PER_CHILD = 100
# # 为存储结果设置过期日期，默认1天过期。如果beat开启，Celery每天会自动清除，0表示永不清理
# # 这里可以设置成0，然后自己创建清理结果的机制，比较好控制
# CELERY_RESULT_EXPIRES = 0
# CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True


# APPID，应用ID，服务商模式下为服务商应用ID，即官方文档中的sp_appid，也可以在调用接口的时候覆盖。
WEIXIN_PAY_APPID = ''
# 微信支付商户号，服务商模式下为服务商户号，即官方文档中的sp_mchid。
WEIXIN_PAY_MCHID = ''
# API v3密钥，
WEIXIN_PAY_APIV3_KEY = ''
# 微信支付完成通知回调url，也可以在调用接口的时候覆盖。
WEIXIN_PAY_NOTIFY_URL = ''
# 商户证书私钥目录
WEIXIN_PAY_PRIVATE_KEY_DIR = os.path.join(BASE_DIR, 'conf', 'cert', 'apiclient_key.pem')
# 商户证书序列号
WEIXIN_PAY_CERT_SERIAL_NO = ''

SUPPORT_FILE_MODELS = ['gpt-4', 'gpt-4o', 'gpt-4-turbo', 'claude-3-5-sonnet-20241022', 'claude-3-5-sonnet-20240620', 'claude-3-haiku-20240307', 'claude-3-opus-20240229', 'claude-3-sonnet-20240229']


cfg_file = os.path.join(BASE_DIR, 'conf', 'config.yaml')
if os.path.exists(cfg_file):
    with open(cfg_file, 'r') as fp:
        custom_settings = yaml.load(fp, Loader=yaml.Loader)
        if custom_settings is not None:
            globals().update(custom_settings)
        else:
            print('load config error: {}'.format(cfg_file))



# from aichat.celery_beat import CELERY_BEAT_SCHEDULE



if DEBUG:
    CORS_ALLOW_CREDENTIALS = True
    CORS_ALLOW_ALL_ORIGINS = True
    CORS_ALLOW_HEADERS = ('*', )
    CORS_ALLOW_HEADERS = [
        "accept",
        "accept-encoding",
        "authorization",
        "content-type",
        "dnt",
        "origin",
        "user-agent",
        "x-csrftoken",
        "x-requested-with",
    ]
    # 配置可跨域访问的 域名/IP
    CORS_ALLOWED_ORIGINS = [
        'http://127.0.0.1:8000',
    ]
    CORS_ALLOW_METHODS = [
        '*', # * 表示允许全部请求头
        'GET',
        'POST',
        'PUT',
        'PATCH',
        'DELETE',
        'OPTIONS'
    ]
    SESSION_COOKIE_SAMESITE = None
    SESSION_COOKIE_SECURE = True
